name: PGNO 85 DevSecOps CI/CD Pipeline

on:
  push:
    branches:
      - main
      - "Core-Pipeline-**"
  pull_request:
      branches:
      - main

jobs:
  build-and-scan:
    name: Build the container and scan
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Secret Scanning with Gitleaks
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: SAST Scanning with Semgrep
        uses: returntocorp/semgrep-action@v1
        continue-on-error: true
        with:
          config: p/java

      - name: IaC Security Scanning with Checkov
        uses: bridgecrewio/checkov-action@master
        continue-on-error: true
        with:
          directory: .
          framework: dockerfile

      - name: Setup JDK 25 For WebGoat
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Build WebGoat
        run: ./mvnw clean package -DskipTests

      - name: SCA Scanning with OWASP Dependency-Check
        run: ./mvnw org.owasp:dependency-check-maven:check -Dformat=HTML -DfailBuildOnCVSS=7
        continue-on-error: true

      - name: Building the docker image
        run: docker build -t webgoat-local:latest .

      - name: Vulnerability Scannig with Trivy (OS and dependency scans)
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: 'webgoat-local:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
